### ISSUE TITLE
More sources for artists

### ISSUE THREAD

**Issue by alastair** [MTG/echonest-backup#1]
Echo Nest lets you query by foreign IDs and also text search. We should look up artist ids from
- MusicBrainz artist mbids
- Text search from the discogs dump
- IDs from other catalogs (7digital, rdio, Free music archive) if people can supply us with the data

**Comment by alastair** [comment]
rosetta stone also knows about discogs artist ids, we could start with this before doing search

**Comment by gearmonkey** [comment]
also, you can spider from within the echonest via some queries. For example http://developer.echonest.com/docs/v4/artist.html#top-hottt which at least based on the documentation has no threshold so might be a means to page through every artist in order of current hotttnesss.
…
after poking at that end point after about 900 pages it starts returning 400 instead of 200 if you ask for further pages with the page size set to the max of 100. So I'll just shy of one hundred thousand artist id, name and hotttnesss triples and stash them in a gist. It should have some recently popular stuff in it that might be missed by the other id sources.
