### ISSUE TITLE
Database 

### ISSUE THREAD

**Issue by andrebola** [MTG/echonest-backup#2]
We should have a database to store the results. This is the schema (for Postgresql 9.5) that we talked:

```
CREATE TABLE mappings (
  id INTEGER,
  queryid VARCHAR NOT NULL,
  entity VARCHAR NOT NULL,
  data jsonb not null,
  date DATETIME WITH TIME ZONE,
);
```

**Comment by alastair** [comment]
the `id` field should be a serial.

In AcousticBrainz we split the json data into a separate table, with the id field a FK to the main data table. This way we can join the metadata against other tables more easily.

We could add additional tables `echonest_artist` and `echonest_song` containing the available ids that we want to query. Join against the `mappings` table to find items that aren't looked up.
Sometimes IDs that exist have no response from echonest. we should store them in the mappings table so that we know they were looked up, but they will have no data.

**Comment by 149203** [comment]
@andrebola @alastair What's your status on this? I may be able to contribute if you're still doing it. Looks like you've stopped. Cheers!

**Comment by alastair** [comment]
Hi,
I have some contributions which I need to push. I'll do this on Monday.

**Comment by alastair** [comment]
Database interface merged
